#include "sequence-for.hpp"

#define zip_to_macro(step, a, b) SF_FOR_EACH(DETAIL_ZIP_FOREACH_BODY, DETAIL_ZIP_FOREACH_STEP, SF_NULL, (step, b), a)

#define DETAIL_ZIP_FOREACH_BODY(n, d, ...) DETAIL_ZIP_FOREACH_BODY_1(n, (__VA_ARGS__), IDENTITY d)
#define DETAIL_ZIP_FOREACH_BODY_1(...) DETAIL_ZIP_FOREACH_BODY_2(__VA_ARGS__)
#define DETAIL_ZIP_FOREACH_BODY_2(n, a_elem, step, b) step(a_elem, (DETAIL_ZIP_FOREACH_SEQ_FIRST(b)))

#define DETAIL_ZIP_FOREACH_STEP(n, d, ...) DETAIL_ZIP_FOREACH_STEP_1(n, IDENTITY d)
#define DETAIL_ZIP_FOREACH_STEP_1(...) DETAIL_ZIP_FOREACH_STEP_2(__VA_ARGS__)
#define DETAIL_ZIP_FOREACH_STEP_2(n, step, b) (step, DETAIL_ZIP_FOREACH_EMPTY b)

#define DETAIL_ZIP_FOREACH_EMPTY(...)
#define IDENTITY(...) __VA_ARGS__

#define DETAIL_ZIP_FOREACH_SEQ_FIRST(...) DETAIL_ZIP_FOREACH_SEQ_FIRST_ __VA_ARGS__ )
#define DETAIL_ZIP_FOREACH_SEQ_FIRST_(...) __VA_ARGS__ DETAIL_ZIP_FOREACH_EMPTY(
